### PR TITLE
List messages example

### PR DESCRIPTION
**Pull request by neekolas**
## Summary

Simple example of getting a profile by ID and listing messages for that profile. A lot of the code was borrowed from the `get-profile` example.

I had to make a second Lens profile `0x4814` and register it with the XMTP dev network for this to work.

### CODE REVIEW

**Review by elisealix22 — APPROVED** [review]
🥲 it's beautiful!

**Comment by joshstevens19** [comment]
Oh boy! Thanks for this 👍

**Comment by joshstevens19** [comment]
How easy is that ❤️❤️❤️

**Comment by neekolas** [comment]
Got a little over-excited and made the PR to the wrong repo. Moved it over to [our fork here](https://github.com/xmtp/lens-api-examples/pull/1).

I'm just starting to try and get my head around how the two protocols can compose together nicely.

**Comment by joshstevens19** [comment]
Makes sense! Obviously this is just API examples we be wrapping your sdk in one we will build but so cool to see

**Pull request closed without merging**
